package oh;

/**
 * This class provides the properties that are needed to be loaded for
 * setting up To Do List Maker workspace controls including language-dependent
 * text.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum OfficeHoursPropertyType {

    /* THESE ARE THE NODES IN OUR APP */
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OH_OK_PROMPT,
    OH_CANCEL_PROMPT,

    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    OH_LEFT_PANE,
    OH_TAS_HEADER_PANE,
    OH_TAS_HEADER_LABEL,
    OH_GRAD_UNDERGRAD_TAS_PANE,
    OH_ALL_RADIO_BUTTON,
    OH_GRAD_RADIO_BUTTON,
    OH_UNDERGRAD_RADIO_BUTTON,
    OH_TAS_HEADER_TEXT_FIELD,
    OH_TAS_TABLE_VIEW,
    OH_NAME_TABLE_COLUMN,
    OH_EMAIL_TABLE_COLUMN,
    OH_SLOTS_TABLE_COLUMN,
    OH_TYPE_TABLE_COLUMN,
HOME_CB,  SYLLABUS_CB,SCHEDULE_CB,HW_CB,  SUBJECT_COMBO,FONTSHEET,
    SEMESTER_COMBO,
    NUMBER_COMBO,
    YEAR_COMBO,
    SCHEDULE_TITLE,
    SCHEDULE_TOPIC,
    SCHEDULE_LINK,
    SCHEDULE_TYPE_COMBO,
    DATE_CHOOSE,
    OH_ADD_TA_PANE,
    OH_NAME_TEXT_FIELD,
    OH_EMAIL_TEXT_FIELD,
    INSTRUCTOR_NAME_TEXT_FIELD,
    INSTRUCTOR_EMAIL_TEXT_FIELD,
    INSTRUCTOR_ROOM_TEXT_FIELD,
    INSTRUCTOR_HP_TEXT_FIELD,
    INSTRUCTOR_TEXT_AREA,
    OH_ADD_TA_BUTTON,
    
    DESCRIPTION_TEXT_AREA,
    TOPICS_TEXT_AREA,
    PPREREQUISITES_TEXT_AREA,
    OUTCOMES_TEXT_AREA,
    BOOKS_TEXT_AREA,
    GRADING_COMPONENTS_TEXT_AREA,
    GRADING_NOTES_TEXT_AREA,
    AD_TEXT_AREA,
    SPEC_ASSIS_TEXT_AREA,
    FAVICON_IMAGE,
    NAVBAR_IMAGE,
    LEFT_FOOTER,
    RIGHT_FOOTER,
SECTION_COLUMN,
DAYS_COLUMN,
TIME_COLUMN,
ROOM_COLUMN,
SCHEDULE_TABLE,
    LECTURES_TABLE_VIEW,
    RECITATION_SECTION_COLUMN,
    RECITATION_TABLE,
    DAYSANDTIME_COLUMN,
    RECITAION_ROOM_COLUMN,
    TA1_COLUMN,
    TA2_COLUMN,
    LABS_SECTION_COLUMN,
    LABS_TABLE,
    LABS_DAYSANDTIME_COLUMN,
    LABS_ROOM_COLUMN,
    LABS_TA1_COLUMN,
    LABS_TA2_COLUMN,
    STYPE_COLUMN,
    SDATE_COLUMN,
    STITLE_COLUMN,
    STOPIC_COLUMN,
    OH_RIGHT_PANE,
    OH_OFFICE_HOURS_HEADER_PANE,
    OH_OFFICE_HOURS_HEADER_LABEL,
    OH_OFFICE_HOURS_TABLE_VIEW,
    OH_START_TIME_TABLE_COLUMN,
    OH_END_TIME_TABLE_COLUMN,
    OH_MONDAY_TABLE_COLUMN,
    OH_TUESDAY_TABLE_COLUMN,
    OH_WEDNESDAY_TABLE_COLUMN,
    OH_THURSDAY_TABLE_COLUMN,
    OH_FRIDAY_TABLE_COLUMN,
    OH_DAYS_OF_WEEK,
    OH_FOOLPROOF_SETTINGS,
    
    // FOR THE EDIT DIALOG
    OH_TA_EDIT_DIALOG,
    OH_TA_DIALOG_GRID_PANE,
    OH_TA_DIALOG_HEADER_LABEL, 
    OH_TA_DIALOG_NAME_LABEL,
    OH_TA_DIALOG_NAME_TEXT_FIELD,
    OH_TA_DIALOG_EMAIL_LABEL,
    OH_TA_DIALOG_EMAIL_TEXT_FIELD,
    OH_TA_DIALOG_TYPE_LABEL,
    OH_TA_DIALOG_TYPE_BOX,
    OH_TA_DIALOG_GRAD_RADIO_BUTTON,
    OH_TA_DIALOG_UNDERGRAD_RADIO_BUTTON,
    OH_TA_DIALOG_OK_BOX,
    OH_TA_DIALOG_OK_BUTTON, 
    OH_TA_DIALOG_CANCEL_BUTTON, 
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    OH_NO_TA_SELECTED_TITLE, OH_NO_TA_SELECTED_CONTENT
}